### ISSUE TITLE
Create too many thread in mysql_handler.rs

### ISSUE THREAD

**Issue by yuhongye** [datafusedev/fuse-query#10]
In the mysql_handler.rs start() function，it will create a thread pool:
`pub fn start(&self) -> FuseQueryResult<()> {
        let listener =
            net::TcpListener::bind(format!("0.0.0.0:{}", self.opts.mysql_handler_port)).unwrap();

        let pool = ThreadPool::new(4096);
`
When I use my mac book pro to run fuse-query, a failed occur: 
`thread 'tokio-runtime-worker' panicked at 'called Result::unwrap() on an `Err` value: Os { code: 35, kind: WouldBlock, message: "Resource temporarily unavailable" }', /Users/caoxiaoyong/.cargo/registry/src/github.com-1ecc6299db9ec823/threadpool-1.8.1/src/lib.rs:777:10
stack backtrace:
   0:        0x1082a43ac - std::backtrace_rs::backtrace::libunwind::trace::hd4e4f36eb9f0f866
                               at /rustc/11c94a197726b6a981828cb1837d7c3eed1b841d/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:        0x1082a43ac - std::backtrace_rs::backtrace::trace_unsynchronized::h713e8299cd20066f
                               at /rustc/11c94a197726b6a981828cb1837d7c3eed1b841d/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x1082a43ac - std::sys_common::backtrace::_print_fmt::h10db128357fb183a
                               at /rustc/11c94a197726b6a981828cb1837d7c3eed1b841d/library/std/src/sys_common/backtrace.rs:67:5
   3:        0x1082a43ac - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::ha6f5ddd5259d3e16
                               at /rustc/11c94a197726b6a981828cb1837d7c3eed1b841d/library/std/src/sys_common/backtrace.rs:46:22
   4:        0x1082c001d - core::fmt::write::hefe95a44532fe6ed
                               at /rustc/11c94a197726b6a981828cb1837d7c3eed1b841d/library/core/src/fmt/mod.rs:1078:17
   5:        0x10829fac6 - std::io::Write::write_fmt::hf513c99961415bff
                               at /rustc/11c94a197726b6a981828cb1837d7c3eed1b841d/library/std/src/io/mod.rs:1519:15
   6:        0x1082a62b9 - std::sys_common::backtrace::_print::he8e57200c2a0a691
                               at /rustc/11c94a197726b6a981828cb1837d7c3eed1b841d/library/std/src/sys_common/backtrace.rs:49:5
   7:        0x1082a62b9 - std::sys_common::backtrace::print::hab21ea437dd3480e
                               at /rustc/11c94a197726b6a981828cb1837d7c3eed1b841d/library/std/src/sys_common/backtrace.rs:36:9
   8:        0x1082a62b9 - std::panicking::default_hook::{{closure}}::h70a3a940826edea5
                               at /rustc/11c94a197726b6a981828cb1837d7c3eed1b841d/library/std/src/panicking.rs:208:50
   9:        0x1082a5e40 - std::panicking::default_hook::h9520f36dd50be056
                               at /rustc/11c94a197726b6a981828cb1837d7c3eed1b841d/library/std/src/panicking.rs:225:9
  10:        0x1082a693b - std::panicking::rust_panic_with_hook::h102f8bee4e0ef4c7
                               at /rustc/11c94a197726b6a981828cb1837d7c3eed1b841d/library/std/src/panicking.rs:591:17
  11:        0x1082a6465 - std::panicking::begin_panic_handler::{{closure}}::hb72eee9aad2e147c
                               at /rustc/11c94a197726b6a981828cb1837d7c3eed1b841d/library/std/src/panicking.rs:497:13
  12:        0x1082a4868 - std::sys_common::backtrace::__rust_end_short_backtrace::h372ff87ecb2667f3
                               at /rustc/11c94a197726b6a981828cb1837d7c3eed1b841d/library/std/src/sys_common/backtrace.rs:141:18
  13:        0x1082a63ca - rust_begin_unwind
                               at /rustc/11c94a197726b6a981828cb1837d7c3eed1b841d/library/std/src/panicking.rs:493:5
  14:        0x1082ce8ef - core::panicking::panic_fmt::h261fd45d36f74dfa
                               at /rustc/11c94a197726b6a981828cb1837d7c3eed1b841d/library/core/src/panicking.rs:92:14
  15:        0x1082ce7f5 - core::option::expect_none_failed::hf2a36714418ff407
                               at /rustc/11c94a197726b6a981828cb1837d7c3eed1b841d/library/core/src/option.rs:1268:5
  16:        0x10810a2e2 - threadpool::spawn_in_pool::hf5127a9147a81622
  17:        0x108109e67 - threadpool::Builder::build::hbfe641a452a12f1e
  18:        0x10810a0b6 - threadpool::ThreadPool::new::h36ebd4c5ae8c87c6
  19:        0x108081646 - fuse_query::servers::mysql::mysql_handler::MySQLHandler::start::h6b0310d2b8b54387
  20:        0x10802d226 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h2f71a80a373508ff
  21:        0x10803079e - tokio::runtime::task::core::Core<T,S>::poll::hb3c0728aebbf4b3f
  22:        0x108028448 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h36c2507424199f31
  23:        0x1080251cb - tokio::runtime::task::harness::Harness<T,S>::poll::h45dd6c7e49284806
  24:        0x108267cd8 - std::thread::local::LocalKey<T>::with::h162dda8b5d89bc0e
  25:        0x1082710b6 - tokio::runtime::thread_pool::worker::Context::run_task::he46df3ea7ce91956
  26:        0x10827035b - tokio::runtime::thread_pool::worker::Context::run::h63705a7d38108a39
  27:        0x108265e23 - tokio::macros::scoped_tls::ScopedKey<T>::set::h336c692f64a9e74e
  28:        0x1082701cd - tokio::runtime::thread_pool::worker::run::h03f0c263fd4dd28d
  29:        0x108257640 - tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut::he0230cd105d9acc3
  30:        0x108254443 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hcdd61b3f981481cb
  31:        0x108257e38 - tokio::runtime::task::raw::poll::h7ecfdb64b9ae978c
  32:        0x10826d7e3 - tokio::runtime::blocking::pool::Inner::run::h8c4016b5ae5b81af
  33:        0x10826051a - std::sys_common::backtrace::__rust_begin_short_backtrace::h46a045006015dc24
  34:        0x108256896 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h8662e0c5f894df07
  35:        0x1082a9a3d - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h1658d06ba2d41cb5
                               at /rustc/11c94a197726b6a981828cb1837d7c3eed1b841d/library/alloc/src/boxed.rs:1328:9
  36:        0x1082a9a3d - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h747cc083e7349205
                               at /rustc/11c94a197726b6a981828cb1837d7c3eed1b841d/library/alloc/src/boxed.rs:1328:9
  37:        0x1082a9a3d - std::sys::unix::thread::Thread::new::thread_start::h93dd3097fa4fa219
                               at /rustc/11c94a197726b6a981828cb1837d7c3eed1b841d/library/std/src/sys/unix/thread.rs:71:17
  38:     0x7fff7057e109 - __pthread_start
^Cmake: *** [run] Interrupt: 2
`
I noticed `start()` function will create 4096 threads, when I changed the number of thread be 128, all thing is right.

**Comment by sundy-li** [comment]
Ok, maybe we should set the default value to `512`, and introduce a custom setting for that.
