### ISSUE TITLE
MergeProcessor should respect the origin source order

### ISSUE THREAD

**Issue by sundy-li** [datafusedev/fuse-query#12]
```
mysql> select number from system.numbers_mt(20) limit 3;
+--------+
| number |
+--------+
|      0 |
|      1 |
|      4 |
+--------+
3 rows in set (0.00 sec)

```

**Comment by BohuTANG** [comment]
Yes.
But it's hard to do without order by clause, any ideas?

**Comment by sundy-li** [comment]
Just use vector instead of channel by default?

**Comment by BohuTANG** [comment]
Merge processor is dependened on the tokio scheduler(spawn), I think the sequence of merge processor is not the place to rush to solve, fuse-query will do `limit` push down later, then the result is make sense.
