### ISSUE TITLE
how to run fusequery-v0.1.1-alpha-linux-armv7

### ISSUE THREAD

**Issue by l1t1** [datafusedev/fuse-query#21]
```
:~/fuse$ ./fusequery-v0.1.1-alpha-linux-armv7 
=== Exagear internal error ===
pid = 10299
tid = 10299
cpu = 4
argv[0] = /opt/exagear/ubt_a32a64
prctl(PR_SET_MM_MAP) failed: Invalid argument
已放弃 (核心已转储)
```

**Comment by BohuTANG** [comment]
What's the platform and os?
fusequery-v0.1.1-alpha-linux-armv7 it works on my Raspberry Pi

**Comment by l1t1** [comment]
~/fuse$ uname -a
Linux kylin 4.4.131-20200710.kylin.desktop-generic #kylin SMP Fri Jul 10 13:46:24 CST 2020 aarch64 aarch64 aarch64 GNU/Linux

~/fuse$ lsb_release -a
No LSB modules are available.
Distributor ID:	Kylin
Description:	Kylin V10
Release:	V10
Codename:	juniper

~/fuse$ cat /proc/cpuinfo |more
processor	: 0
model name	: HUAWEI,Kunpeng 920
bogomips	: 7200.00
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics
flags		: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics
CPU implementer	: 0x48
CPU architecture: 8
CPU variant	: 0x1
CPU part	: 0xd01
CPU revision	: 0

**Comment by BohuTANG** [comment]
the aarch64 target is ok, it seems [exagear](https://www.huaweicloud.com/kunpeng/software/exagear.html) throws the error:
argv[0] = /opt/exagear/ubt_a32a64
prctl(PR_SET_MM_MAP) failed: Invalid argument

Can you try sudo ./fusequery-v0.1.1-alpha-linux-armv7?

**Comment by BohuTANG** [comment]
You can try the [x86_64 binary]( https://github.com/datafusedev/fuse-query/releases/download/v0.1.1-alpha/fusequery-v0.1.1-alpha-linux-x86_64), it will transalte to arm arch by exagear.

**Comment by l1t1** [comment]
> You can try the [x86_64 binary](https://github.com/datafusedev/fuse-query/releases/download/v0.1.1-alpha/fusequery-v0.1.1-alpha-linux-x86_64), it will transalte to arm arch by exagear.

~/fuse$ ./fusequery-v0.1.1-alpha-linux-x86_64
bash: ./fusequery-v0.1.1-alpha-linux-x86_64: cannot execute binary file: 可执行文件格式错误

**Comment by BohuTANG** [comment]
I will try to add `aarch64` bianry release this weekend.

**Comment by BohuTANG** [comment]
Please download the `fusequery-v0.1.1-alpha-linux-aarch64
` target release here:
https://github.com/datafusedev/fuse-query/releases/tag/v0.1.1-alpha

It works for me on huawei cloud:
```
root@ecs-a30f:~# arch
aarch64
root@ecs-a30f:~# uname -a
Linux ecs-a30f 4.15.0-70-generic #79-Ubuntu SMP Tue Nov 12 10:36:10 UTC 2019 aarch64 aarch64 aarch64 GNU/Linux
```
![image](https://user-images.githubusercontent.com/172204/105570209-acbaff80-5d82-11eb-9548-40f5668538f3.png)
![image](https://user-images.githubusercontent.com/172204/105570215-b17fb380-5d82-11eb-8cdf-f351b572e67d.png)

**Comment by l1t1** [comment]
thanks. could you attach the pdf of pictures.I  cannot see them now

**Comment by BohuTANG** [comment]
The image on the githubusercontext.com blocked, but it's not very important about this issue, just a work show.

**Comment by l1t1** [comment]
thanks, it works on my machine.
